"""Initial schema: sites, drones, runs, run_files.

Revision ID: 0001
Revises:
Create Date: 2026-07-25

Written by hand rather than autogenerated: the partial index below is
the point of the whole schema and autogenerate does not express it
faithfully.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False, unique=True),
    )

    op.create_table(
        "drones",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("serial_number", sa.String(64), nullable=False, unique=True),
        sa.Column("model", sa.String(64), nullable=False),
        sa.Column("api_key_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "drone_id", sa.Integer(), sa.ForeignKey("drones.id"), nullable=False
        ),
        sa.Column(
            "site_id", sa.Integer(), sa.ForeignKey("sites.id"), nullable=False
        ),
        sa.Column("drone_run_uid", sa.String(64), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("operator", sa.String(120), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "expected_file_count", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "confirmed_file_count", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "total_size_bytes", sa.BigInteger(), nullable=False, server_default="0"
        ),
        sa.Column("defect_detected", sa.Boolean(), nullable=True),
        sa.Column("defect_count", sa.Integer(), nullable=True),
        sa.Column("confidence_score", sa.Numeric(4, 3), nullable=True),
        sa.UniqueConstraint(
            "drone_id", "drone_run_uid", name="uq_runs_drone_uid"
        ),
        sa.CheckConstraint(
            "status IN ('UPLOADING', 'COMPLETED', 'INCOMPLETE', 'ABANDONED')",
            name="ck_runs_status",
        ),
        sa.CheckConstraint(
            "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)",
            name="ck_runs_confidence_range",
        ),
    )

    # The index the list endpoint is built around. Partial on
    # defect_detected: the query only ever asks for defective
    # runs, so indexing the rest would pay for rows that can never be
    # returned. Equality on site first, then the date range, so the
    # scan narrows to the few hundred rows in the window before
    # anything else happens. The plan still sorts: a range predicate on
    # started_at stops the same index from also delivering rows ordered
    # by confidence. Sorting that many rows is free, and leading with
    # confidence instead measured eight times slower.
    op.create_index(
        "idx_runs_defective",
        "runs",
        ["site_id", sa.text("started_at DESC"), sa.text("confidence_score DESC")],
        postgresql_where=sa.text("defect_detected"),
    )

    op.create_index(
        "idx_runs_drone_started", "runs", ["drone_id", sa.text("started_at DESC")]
    )

    # Serves the abandoned-run sweep, which scans by status and idle time.
    op.create_index("idx_runs_status_activity", "runs", ["status", "last_activity_at"])

    op.create_table(
        "run_files",
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("runs.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("file_key", sa.String(512), primary_key=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("run_files")
    op.drop_index("idx_runs_status_activity", table_name="runs")
    op.drop_index("idx_runs_drone_started", table_name="runs")
    op.drop_index("idx_runs_defective", table_name="runs")
    op.drop_table("runs")
    op.drop_table("drones")
    op.drop_table("sites")
