from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.config import get_settings

_settings = get_settings()


def _validate_file_key(value: str) -> str:
    """Reject keys that would escape the run prefix in S3.

    Object keys are built from client-supplied strings, so this is the
    boundary where path traversal has to be stopped: a key like
    `../other-run/x.jpg` would otherwise produce a presigned URL
    granting writes outside this run's prefix.
    """
    if not value or value.startswith("/") or ".." in value.split("/"):
        raise ValueError(f"invalid file key: {value!r}")
    return value


class ManifestFile(BaseModel):
    key: str = Field(max_length=512)
    size_bytes: int | None = Field(default=None, ge=0)

    _check_key = field_validator("key")(_validate_file_key)


class RunCreate(BaseModel):
    """Body of POST /v1/runs.

    `drone_run_uid` is generated by the drone, once per run, and
    resent unchanged on every retry. It is the idempotency key.

    `site_id` names what is being inspected. It is part of the mission,
    not a property of the aircraft, so the drone states it here.
    """

    drone_run_uid: str = Field(max_length=64)
    # Declared per mission rather than derived from the drone: an
    # aircraft is not tied to one site.
    site_id: int = Field(gt=0)
    started_at: datetime
    operator: str | None = Field(default=None, max_length=120)
    files: list[ManifestFile] = Field(min_length=1)

    @field_validator("files")
    @classmethod
    def _check_manifest(cls, files: list[ManifestFile]) -> list[ManifestFile]:
        if len(files) > _settings.max_manifest_files:
            raise ValueError(
                f"manifest exceeds {_settings.max_manifest_files} files"
            )
        keys = {f.key for f in files}
        if len(keys) != len(files):
            raise ValueError("manifest contains duplicate keys")
        return files


class PresignedUpload(BaseModel):
    key: str
    url: str
    expires_in: int


class RunCreated(BaseModel):
    """Response of POST /v1/runs, identical on creation and on replay.

    Only the first slice of presigned URLs is returned: ~18 000 of them
    would be several megabytes of JSON and the last would expire before
    the drone reached it. The rest are pulled from /upload-urls.
    """

    run_id: uuid.UUID
    status: str
    expected_file_count: int
    confirmed_file_count: int
    upload_prefix: str
    upload_urls: list[PresignedUpload]
    already_existed: bool


class UploadUrlsRequest(BaseModel):
    keys: list[str] = Field(min_length=1)

    @field_validator("keys")
    @classmethod
    def _check_keys(cls, keys: list[str]) -> list[str]:
        if len(keys) > _settings.max_upload_urls_per_batch:
            raise ValueError(
                f"at most {_settings.max_upload_urls_per_batch} keys per request"
            )
        return [_validate_file_key(k) for k in keys]


class UploadUrlsResponse(BaseModel):
    urls: list[PresignedUpload]
    unknown_keys: list[str]


class ConfirmedFile(BaseModel):
    key: str = Field(max_length=512)
    size_bytes: int | None = Field(default=None, ge=0)

    _check_key = field_validator("key")(_validate_file_key)


class ConfirmationsRequest(BaseModel):
    files: list[ConfirmedFile] = Field(min_length=1)

    @field_validator("files")
    @classmethod
    def _check_batch(cls, files: list[ConfirmedFile]) -> list[ConfirmedFile]:
        if len(files) > _settings.max_confirmations_per_batch:
            raise ValueError(
                f"at most {_settings.max_confirmations_per_batch} files per batch"
            )
        return files


class ConfirmationsResponse(BaseModel):
    """The drone learns where it stands without an extra round trip.

    `newly_confirmed` differs from the batch size when the batch is a
    replay, which is exactly what makes the call safe to retry.
    """

    run_id: uuid.UUID
    status: str
    newly_confirmed: int
    confirmed_file_count: int
    expected_file_count: int
    unknown_keys: list[str]


class RunSummary(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    drone_id: int
    site_id: int
    status: str
    operator: str | None
    started_at: datetime
    completed_at: datetime | None
    expected_file_count: int
    confirmed_file_count: int
    total_size_bytes: int
    defect_detected: bool | None
    defect_count: int | None
    confidence_score: Decimal | None


class ErrorResponse(BaseModel):
    error_code: str
    message: str
    details: dict | None = None


class CompletionRequest(BaseModel):
    """Body of POST /v1/runs/{id}/completion."""

    defect_detected: bool
    defect_count: int = Field(ge=0)
    confidence_score: Decimal = Field(ge=0, le=1, decimal_places=3)


class CompletionResponse(BaseModel):
    """Outcome of reconciliation.

    `results_recorded` is False on a retry: the analysis values were
    written by the first call and are never overwritten, so the drone
    can tell whether this call stored anything.

    `unverified_keys` is the interesting field: files the drone
    confirmed that are not in the bucket. A non-empty list means the
    drone's view and reality disagree, which is a different fault
    from simply not having finished, and one worth surfacing on its
    own rather than folding into the missing count.
    """

    run_id: uuid.UUID
    status: str
    expected_file_count: int
    confirmed_file_count: int
    verified_file_count: int | None
    missing_file_count: int
    missing_keys: list[str]
    missing_keys_truncated: bool
    unverified_keys: list[str]
    results_recorded: bool
    completed_at: datetime | None


class RunPage(BaseModel):
    items: list[RunSummary]
    next_cursor: str | None


class SweepResponse(BaseModel):
    swept_uploading: int
    swept_incomplete: int
